# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='formatted_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
